# Generated by Django 5.0 on 2023-12-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
